### ISSUE TITLE
How to interpret the output files

### ISSUE THREAD

**Issue by zd1** [fhormoz/caviar#1]
Dear caviar developers, 

Thanks for making this tool. I've been using it to look at some colocalization signals. I see in the output that three files are generated for each trait, with suffixes "_1_post", "_1_hist", "_1_set" (likewise for trait 2), and a "_col" file for the colocalization posteriors. 

Could you explain the meaning of the numbers in the three files for each trait? (there are no headers)

Thanks,
Zhihao

**Comment by fhormoz** [comment]
I am SORRY. I will add the header in the next commit of the code.

*_col contains the colocalization posterior probability (CLPP). CLPP is the probability that the same variant is causal in both GWAS and eQTL. The first column is the variant ID and the last column is the CLPP score. The second column is used for internal purpose.

*_post: contains the probability of each variant is causal in eQTL or GWAS. The last column is this quantity.
The files _1 and _2 generally refer to the GWAS and eQTL, respectively. The second column is the amount that this variant contributes to credible set (95%-causal set).

*_set: is the credible set used for fine-mapping purpose.

**Comment by zd1** [comment]
Thanks very much for the reply! It's very helpful. 

Best,
Zhihao

**Comment by zd1** [comment]
I just realised that I was using version "v1.0 22/Apr/2016", which also outputs a "_hist" file. Would you mind also explaining the columns of this file?

Many thanks,
Zhihao

**Comment by fhormoz** [comment]
The output of caviar when you set -f and if you set the maximum number of causal "-c " to X. Then you will have a *_hist file where you will have X+1 column in the output file as follow:

First Column: The probability that this locus has no causal variants
Second Column: The probability that this locus has 1 causal variant.
X-th Column: The probability that this locus has (X-1) causal variants.

**Comment by zd1** [comment]
Thanks a lot!
