### ISSUE TITLE
LD matrix - r or r2?

### ISSUE THREAD

**Issue by mcgml** [fhormoz/caviar#12]
Just a quick question - the LD matrix is the pairwise Pearson correlation between two SNPs. Should we provide r or r2?

Thanks
Matt

**Comment by fhormoz** [comment]
The LD matrix should be r.

**Comment by mcgml** [comment]
thank you

**Comment by JuRaGa** [comment]
Hi,
I am struggling to get the LD matrices. Do you know any quick way of getting these?
Thank you,
Julia

**Comment by greengarden0925** [comment]
> Hi, I am struggling to get the LD matrices. Do you know any quick way of getting these? Thank you, Julia

You can do it using local file, refer to :https://cran.r-project.org/web/packages/ieugwasr/vignettes/local_ld.html.
Or do it through API https://mrcieu.github.io/ieugwasr/articles/local_ld.html
