### ISSUE TITLE
rm: cannot remove ‘CAVIAR’: No such file or directory

### ISSUE THREAD

**Issue by JuRaGa** [fhormoz/caviar#13]
Hi,
This is the first time I try to use CAVIAR.
I have followed the instructions and cloned it as in "git clone https://github.com/fhormoz/caviar.git"

However, I don't see any executable names "CAVIAR" in any folder.

I have also downloaded and installed the the GNU scientific library. When I type "make clean" in the caviar/CAVIAR C++ repository, I get this error:

 CAVIAR-C++]$ make clean
rm CAVIAR
rm: cannot remove ‘CAVIAR’: No such file or directory
make: *** [clean] Error 1
 CAVIAR-C++]$

So I am not really sure what is happening? I would appreciate your help.
Thank you,
Julia

**Comment by eshaikho** [comment]
Hi Julia,
Make sure you have these two libraries installed too (lapack-devel & blas-devel).
You can then run make or make clean. The only difference between make and make clean is that make clean will remove the intermediate files in that directory.

**Comment by oyhel** [comment]
If on ubuntu 18.04 run: 
sudo apt install libgsl-dev libblas-dev liblapack-dev
