### ISSUE TITLE
Unable to run eCAVIAR with >8k SNPs

### ISSUE THREAD

**Issue by heinin** [fhormoz/caviar#18]
I'm having trouble running eCAVIAR when the number of SNPs is large, >8k. Jobs with fewer SNPs run without a problem, and increasing the available memory doesn't seem to be making a difference. Any tips? Thank you!

**Comment by fhormoz** [comment]
Yes. It is better for eCAVIAR to have fewer than 1000 SNPs. I would recommend filtering out variants that have P-value > 0.05. Please make sure that the variants in both gene expression and GWAS are the same and in the same order.
