### ISSUE TITLE
analysis per gene is it?

### ISSUE THREAD

**Issue by complexgenome** [fhormoz/caviar#19]
hello devs,

I understand ecaviar is awesome, works fast. However, the input data eQTL and GWAS are per gene? 
If I have 20 genes, I believe ecaviar isn't scalable? 

edit: ecaviar

**Comment by fhormoz** [comment]
You need to run eCAVIAR per gene. However, as each gene are independent you can run each gene on a different machine, thus, very easy to run on cluster that have multiple CPUs.
