### ISSUE TITLE
web site not work

### ISSUE THREAD

**Issue by zpliu1126** [fhormoz/caviar#25]
Hi~ fhormoz

Has the software documentation moved elsewhere? I can't open the web site  http://genetics.cs.ucla.edu/caviar/

Your help will be appreciated.

**Comment by fhormoz** [comment]
Hi Zpliu,

I am not sure why UCLA webpage is not working for some folks. I know for a fact that works for some folks outside UCLA network and I just checked it. However, I heard that some other folks can not access it. In any case, the UCLA webpage info is a subset of this Github page.
