### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by xtmgah** [fhormoz/caviar#3]
Hello: 

I am trying the caivar on the eQTL and GWAS data for few GWAS loci. However, some loci are completed and some loci had a error information like "segmentation fault"... Here i gave a example. Here is the output from my command. Could you help to check and fix this error? Thanks so much. 

 eCAVIAR -l test_GWAS.ld -l test_eQTL.ld -z test_GWAS.z -z test_eQTL.z -o output 

@-------------------------------------------------------------@
| eCAVIAR!     	| 	   v2.0         |  01/Aug/2017 | 
|-------------------------------------------------------------|
| (C) 2017 Farhad Hormozdiari, GNU General Public License, v2 |
|-------------------------------------------------------------|
| For documentation, citation & bug-report instructions:      |
| 		http://genetics.cs.ucla.edu/caviar/            |
@-------------------------------------------------------------@
-0	0
add
0	0.1
add
0	0.2
add
0	0.3
add
0	0.4
add
0	0.5
add
4.94066e-324	0.6
FINISH
reach=2659
2659
Max Causal=2
Total=3536471
0 5.67241e-23
100000 4.2641e-17
200000 4.98178e-17
300000 5.67564e-17
400000 6.55714e-17
500000 7.24377e-17
600000 8.29678e-17
700000 9.06624e-17
800000 9.79103e-17
900000 1.03529e-16
1000000 1.09101e-16
1100000 1.15797e-16
1200000 1.22241e-16
1300000 1.29166e-16
1400000 1.36004e-16
1500000 1.47125e-16
1600000 1.55799e-16
1700000 1.64667e-16
1800000 1.74226e-16
1900000 1.81991e-16
2000000 1.90807e-16
2100000 2.01153e-16
2200000 2.14104e-16
2300000 2.34897e-16
2400000 3.31121e-16
2500000 7.22409e-13
2600000 7.22409e-13
2700000 7.22409e-13
2800000 7.22409e-13
2900000 7.22409e-13
3000000 7.22409e-13
3100000 7.22409e-13
3200000 7.22409e-13
3300000 7.22409e-13
3400000 7.22409e-13
3500000 7.22409e-13
Total Likelihood= 1.444780e-12 SNP=2659 

1183 4.850940e-01

-0	0
add
0	0.1
add
0	0.2
add
0	0.3
add
0	0.4
add
0	0.5
add
4.94066e-324	0.6
Segmentation fault

The data can be download here:

https://www.dropbox.com/sh/d3wspkfm5csknk5/AABAhXeqWbfakgTBX8LJnwPpa?dl=0

**Comment by zpliu** [comment]
I used the latest version, but still same issue. Seems no one responses. 

@-------------------------------------------------------------@
| eCAVIAR!      |          v2.2         |  10/Apr/2018        |
|-------------------------------------------------------------|
| (C) 2018 Farhad Hormozdiari, GNU General Public License, v2 |
|-------------------------------------------------------------|
| For documentation, citation & bug-report instructions:      |
|               http://genetics.cs.ucla.edu/caviar/           |
@-------------------------------------------------------------@
Segmentation fault      (core dumped)

**Comment by fhormoz** [comment]
I think most probability your LD or Z-score file has nan. Can you convert nan to 0?
Please let me know if you still have the Segmentation fault. I will try to fix this in the next 
version to output a warning if the files have nan.

**Comment by zpliu** [comment]
> I think most probability your LD or Z-score file has nan. Can you convert nan to 0?
Please let me know if you still have the Segmentation fault. I will try to fix this in the next
version to output a warning if the files have nan.

 @fhormoz  Thanks for the reply. I think it is caused by nan value. I did not check the LD matrix very carefully at the beginning. Later, I only pick SNPs that existed in the 1KG data (thus no nan value), it works fine. 

BTW, I noticed in the latest version, there are sample data for colocalization analysis (eQTL.CARDIOGENICS.MC.AD.IGAP.stage1.hg19.chr.11.121344805.121517613.CHRPOSREFALT.ILMN_1810712.NM_015313.1.ARHGEF12.Z.txt and GWAS.MC.AD.IGAP.stage1.hg19.chr.11.121344805.121517613.CHRPOSREFALT.Z.txt). They have the exactly same SNPs but rho values in ld files are different. Why is this?
