### ISSUE TITLE
GSL error

### ISSUE THREAD

**Issue by kathush** [fhormoz/caviar#6]
Hello, 

I'm trying to run CAVIAR, not very successfully..

I tried first with my own data, but it kept failing. I tried with the sample data that you provide and I get the same error. 
This is my code: 
`./CAVIAR –l /cvar/jhlab/Kathy/Plink/caviar/CAVIAR-C++/sample_data/50_LD.txt –z /cvar/jhlab/Kathy/Plink/caviar/CAVIAR-C++/sample_data/50_Z.txt –r 0.95 –o outputresults`

And this is the error that I keep getting: 
`gsl: init_source.c:29: ERROR: matrix dimension n1 must be positive integer
Default GSL error handler invoked.
Aborted (core dumped)`

Do you have any suggestions what should I change in order to fix this? 
Can you also comment which file formats can CAVIAR tolerate? only .txt and .ld? or also .csv? 

Thank you!

**Comment by fhormozdiari** [comment]
Hi,

This is very strange. Can you please run "make clean" and run "make" command. Then, run the sample code. Usually, I get this error when I run CAVAIR without specifying the LD or Z-score file or using the
Z-score file instead of LD file. 

CAVIAR inputs should be tab/space delimiters. The Z-score file contains the SNPID and Z-scores.
The LD files is a (n*n) matrix where n is the number of SNPs in a locus.

Thanks,

**Comment by kathush** [comment]
Hi Farhad, 

Sorry about the delay -
I reinstalled the program and ran `make clear` followed by `make`. By running the sample code you mean just to execute `./CAVIAR`? When I do that I get the same error as previously. 
I have GCC, Python, GSL and openblas loaded. 
I also noticed that each time I'm trying to run something, an -rw file "core.xxxxx" is created in the directory. 

Any clues what might be going on?
Thanks!
Kathy

**Comment by fhormozdiari** [comment]
Hi Kathy,

After you make the program.

1) Run the program as follow: ./CAVIAR -h
I expect that it will show a short manual of CAVIAR. 

2) Run the sample data as follow:
./CAVAIR -z sample_data/50_Z.txt -l sample_data/50_LD.txt -c 2 -o test -f 1 -r 0.95

Please let me know if any of these commands failed.

In addition, can you email me the output of these result at hormozdiari@hsph.harvard.edu

Thanks
