### ISSUE TITLE
Why compute dmvnorm(Zcc, mean=rep(0,nrow(Rcc)), Rcc + Rcc %*% Rcc) / dmvnorm(Zcc, rep(0, nrow(Rcc)), Rcc))？

### ISSUE THREAD

**Issue by huanglukang** [fhormoz/caviar#9]
From the caviar paper, I don't see this step however. I wonder why I need to computer this not just compute dmvnorm(Zcc, mean=rep(0,nrow(Rcc)), Rcc + Rcc %*% Rcc).

**Comment by fhormoz** [comment]
Rcc consists of LD for ONLY Causal SNPs. However, if you use all the SNPs and perform dmvnorm(Z, mean=rep(0,nrow(R)), R + R %*% R) where Z is the Z-score of all m SNPs and R is the LD matrix (m*m) then the computation cost is O(m^3) but you can show that we can compute dmvnorm(Zcc, mean=rep(0,nrow(Rcc)), Rcc + Rcc %*% Rcc) / dmvnorm(Zcc, rep(0, nrow(Rcc)), Rcc)) instead, where the Rcc matrix is k*k and k is the number causal SNPs for a configuration (k << m). Thus, in the second case, we only need to inverse a k*k matrix which is much fast than inverting an m*m matrix. This new computation was not part of original CAVIAR paper.

**Comment by huanglukang** [comment]
Thanks for your patient reply.  I want to know what is the true causal SNP for the data "50_LD" and "50_Z"?
